// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function AddDomain(arg1:types.Domain):Promise<void>;

export function CheckAndUpdate(arg1:number):Promise<void>;

export function ClearLogs():Promise<void>;

export function DeleteDomain(arg1:number):Promise<void>;

export function ExportLogs():Promise<string>;

export function GetDomainStatus():Promise<Array<types.DomainStatus>>;

export function GetLogs(arg1:string,arg2:string):Promise<Array<types.LogEntry>>;

export function GetPublicIP():Promise<types.IPInfo>;

export function GetSettings():Promise<types.Settings>;

export function ListDomains():Promise<Array<types.Domain>>;

export function LoadSettings():Promise<types.Settings>;

export function RefreshStatus():Promise<void>;

export function ResetSettings():Promise<void>;

export function SaveSettings(arg1:types.Settings):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartDDNS(arg1:number):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleDomain(arg1:number):Promise<boolean>;

export function UpdateDomain(arg1:types.Domain):Promise<void>;
