// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDomain(arg1) {
  return window['go']['app']['App']['AddDomain'](arg1);
}

export function CheckAndUpdate(arg1) {
  return window['go']['app']['App']['CheckAndUpdate'](arg1);
}

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function DeleteDomain(arg1) {
  return window['go']['app']['App']['DeleteDomain'](arg1);
}

export function ExportLogs() {
  return window['go']['app']['App']['ExportLogs']();
}

export function GetDomainStatus() {
  return window['go']['app']['App']['GetDomainStatus']();
}

export function GetLogs(arg1, arg2) {
  return window['go']['app']['App']['GetLogs'](arg1, arg2);
}

export function GetPublicIP() {
  return window['go']['app']['App']['GetPublicIP']();
}

export function ListDomains() {
  return window['go']['app']['App']['ListDomains']();
}

export function LoadSettings() {
  return window['go']['app']['App']['LoadSettings']();
}

export function RefreshStatus() {
  return window['go']['app']['App']['RefreshStatus']();
}

export function ResetSettings() {
  return window['go']['app']['App']['ResetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function StartDDNS(arg1) {
  return window['go']['app']['App']['StartDDNS'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function ToggleDomain(arg1) {
  return window['go']['app']['App']['ToggleDomain'](arg1);
}

export function UpdateDomain(arg1) {
  return window['go']['app']['App']['UpdateDomain'](arg1);
}
